#!/bin/bash
usage() {
    echo "Usage: $0 -i | --input <input> [OPTIONS]"
    echo "Use --help for more information."
    exit 1
}

# Script to run the full analysis workflow on the raw.txt files generated by the data acquisition script

# Check for help flag first
if [[ "$@" == *"--help"* ]]; then
    echo "Script usage: $0 -i | --input <input> [OPTIONS]"
    echo ""
    echo "REQUIRED ARGUMENTS:"
    echo "  -i | --input <input>                  Path to the raw data (file or directory) to analyze"
    echo ""
    echo "OPTIONS:"
    echo "  -s | --self                           Used self-trigger firmware during acquisition"
    echo "  --dt-max <dt_max>                     Maximum time window for efficiency (default: -100)"
    echo "  --dt-min <dt_min>                     Minimum time window for efficiency (default: -180)"
    echo "  -e | --error-type <error_type>        Specify the error type for efficiency calculations (default: 'binomial'). Valid options: 'binomial', 'clopper-pearson'."
    echo "  --no-external                         Disable external trigger usage in analysis"
    echo "  --old-data-type                       Whether to use old data type (default: false)"
    echo "  -r | --recompile                      Force recompilation of the main analysis executable before running"
    echo "  -h | --help                           Display this help message"
    echo ""
    echo "EXAMPLES:"
    echo "  $0 -i /root/data/raw/raw_data.txt --dt-max -120 --dt-min -200"
    exit 0
fi

# Check for required arguments
if [ "$#" -lt 2 ]; then
    echo "ERROR: Missing required arguments."
    usage
fi

# Process CLI arguments
input="$1"
if [ ! -e "$input" ]; then
    echo "ERROR: Input '$input' does not exist."
    exit 1
fi

# Initialize time window parameters with defaults
dt_max="-100"
dt_min="-180"
error_type="Binomial"
recompile=false

# Process flags and optional arguments
shift 1
while [[ "$#" -gt 0 ]]; do
    case "$1" in
        -s|--self)
            use_self_trigger="--self"
            shift
            ;;
        --dt-max)
            dt_max="$2"
            shift 2
            ;;
        --dt-min)
             dt_min="$2"
             shift 2
             ;;
        -e|--error-type)
            error_type="$2"
            shift 2
            ;;
        --no-external)
            no_external="--no-external"
            shift
            ;;
        --old-data-type)
            old_data_type="--use-old-data"
            shift
            ;;
        --recompile)
            recompile=true
            shift
            ;;
        --help|-h)
            usage
            ;;
        *)
            echo "Unknown option: $1"
            usage
            ;;
    esac
done

rootDir="$(dirname "$(dirname "$(realpath "$0")")")"
echo "Root directory: $rootDir"

# Output directory for ROOT files
outputDir="$rootDir/data/output"
if [ ! -d "$outputDir" ]; then
    mkdir -p "$outputDir"
fi

# Recompile main C++ analysis executable if not already compiled
cd "$rootDir"
if [ "$recompile" = true ]; then
    echo "Recompilation requested. Recompiling analysis executable..."
    make rebuild
else
    if [ ! -f "$rootDir/bin/analysis" ]; then
        echo "Analysis executable not found. Compiling..."
        make build
    else
        echo "Analysis executable already exists. Skipping compilation."
    fi
fi

# Run analysis executable on each file to process raw hits and generate ROOT file
if [ -d "$input" ]; then
    echo "Input is a directory. Processing all .txt files in $input..."
    for file in "$input"/*.txt; do
        echo "Processing file: $file"
        "$rootDir/bin/analysis" process --input "$file" --dt-max "$dt_max" --dt-min "$dt_min" --error-type "$error_type" $no_external $old_data_type $reject_background $use_self_trigger
        mv ./output.root "$outputDir"
    done
else
    echo "Input is a single file. Processing $input..."
    "$rootDir/bin/analysis" process --input "$input" --dt-max "$dt_max" --dt-min "$dt_min" --error-type "$error_type" $no_external $old_data_type $reject_background $use_self_trigger
    mv ./output.root "$outputDir"
fi