#!/bin/bash
usage() {
    echo "Usage: $0 <input> [OPTIONS]"
    echo "Use --help for more information."
    exit 1
}

# Script to run the full analysis workflow on the raw.txt files generated by the data acquisition script

# Check for help flag first
if [[ "$@" == *"--help"* ]]; then
    echo "Script usage: $0 <input> [OPTIONS]"
    echo ""
    echo "REQUIRED ARGUMENTS:"
    echo "  <input>             Path to the raw data (file or directory) to analyze"
    echo ""
    echo "OPTIONS:"
    echo "  -s, --self          Used self-trigger firmware during acquisition"
    echo "  --dt-max VALUE      Maximum time window for efficiency (default: -100)"
    echo "  --dt-min VALUE      Minimum time window for efficiency (default: -180)"
    echo "  --old-data-type     Whether to use old data type (default: false)"
    echo "  --no-external       Disable external trigger usage in analysis"
    echo "  -h, --help          Display this help message"
    echo ""
    echo "EXAMPLES:"
    echo "  $0 /root/data/raw/raw_data.txt --dt-max -120 --dt-min -200"
    exit 0
fi

# Check for required arguments
if [ "$#" -lt 1 ]; then
    echo "ERROR: Missing required arguments."
    usage
fi

# Process CLI arguments
input="$1"
if [ ! -e "$input" ]; then
    echo "ERROR: Input '$input' does not exist."
    exit 1
fi

# Initialize time window parameters with defaults
dt_max="-100"
dt_min="-180"

# Process flags and optional arguments
shift 1
while [[ "$#" -gt 0 ]]; do
    case "$1" in
        -s|--self)
            use_self_trigger="--self"
            shift
            ;;
        --dt-max)
            dt_max="$2"
            shift 2
            ;;
        --dt-min)
             dt_min="$2"
             shift 2
             ;;
        --no-external)
            no_external="--no-external"
            shift
            ;;
            echo "Unknown option: $1"
            usage
            ;;
        --old-data-type)
            old_data_type="--use-old-data"
            shift
            ;;
        --help|-h)
            usage
            ;;
        *)
            echo "Unknown option: $1"
            usage
            ;;
    esac
done

rootDir="$(dirname "$(dirname "$(realpath "$0")")")"
echo "Root directory: $rootDir"

# Output directory for ROOT files
outputDir="$rootDir/data/output"
if [ ! -d "$outputDir" ]; then
    mkdir -p "$outputDir"
fi

# Recompile main C++ analysis executable if not already compiled
cd "$rootDir"
echo "Compiling main analysis executable..."
make build

# Run analysis executable on each file to process raw hits and generate ROOT file
if [ -d "$input" ]; then
    echo "Input is a directory. Processing all .txt files in $input..."
    for file in "$input"/*.txt; do
        echo "Processing file: $file"
        "$rootDir/bin/analysis" process "$file" "$dt_max" "$dt_min" $no_external $old_data_type $use_self_trigger
        mv ./output.root "$outputDir"
    done
else
    echo "Input is a single file. Processing $input..."
    "$rootDir/bin/analysis" process "$input" "$dt_max" "$dt_min" $no_external $old_data_type $use_self_trigger
    mv ./output.root "$outputDir"
fi