#!/bin/bash

# Script to run the full analysis workflow on the raw.txt files generated by the data acquisition script

# Check for help flag first
if [[ "$@" == *"--help"* ]]; then
   echo "Script usage: $0 <input> [OPTIONS]"
   echo ""
   echo "REQUIRED ARGUMENTS:"
   echo "  <input>             Path to the raw data (file or directory) to analyze"
   echo ""
   echo "OPTIONS:"
   echo "  -s, --self          Used self-trigger firmware during acquisition"
   echo "  --dt-max VALUE      Maximum time window for efficiency (default: -100)"
   echo "  --dt-min VALUE      Minimum time window for efficiency (default: -180)"
   echo "  -h, --help          Display this help message"
   echo ""
   echo "EXAMPLES:"
   echo "  $0 /root/data/raw/raw_data.txt --batch --dt-max -120 --dt-min -200"
   exit 0
fi

# Check for required arguments
if [ "$#" -lt 2 ]; then
   echo "ERROR: Missing required arguments."
   echo "Usage: $0 <input> [OPTIONS]"
   echo "Use --help for more information."
   exit 1
fi

# Process CLI arguments
input="$1"
if [ ! -d "$rawDir" ]; then
    echo "ERROR: Raw data directory '$rawDir' does not exist."
    exit 1
fi

# Compile main C++ analysis executable if not already compiled
cd "$rootDir"
if [ ! -f "$rootDir/bin/analysis" ]; then
    echo "Compiling main analysis executable..."
    make build
fi

# Run analysis executable on each file to process raw hits and generate ROOT file
if [ -d "$input" ]; then
    echo "Input is a directory. Processing all .txt files in $input..."
    for file in "$input"/*.txt; do
        echo "Processing file: $file"
        "$rootDir/bin/analysis" "$file" "$dt_max" "$dt_min" $use_self_trigger
        rootfile_name="$outputFileName.root"
        mv ./output.root "$outputDir/$rootfile_name"
    done
else
    echo "Input is a single file. Processing $input..."
    "$rootDir/bin/analysis" "$input" "$dt_max" "$dt_min" $use_self_trigger
    rootfile_name="$outputFileName.root"
    mv ./output.root "$outputDir/$rootfile_name"
fi